#!/bin/bash

# setup.sh - automatic installation and configuration for WSBG Terminal
# Supports macOS and Linux

set -e

echo "=========================================="
echo "   WSBG Terminal - Setup & Installation   "
echo "=========================================="

# 1. Install/Update Ollama
# The install script handles both fresh installs and in-place updates. Exits
# quickly when already current. Keeping Ollama up-to-date prevents model pull
# failures caused by version incompatibilities with newer model formats.
echo "[*] Installing/updating Ollama..."
curl -fsSL https://ollama.com/install.sh | sh || echo "    [WARN] Ollama install/update failed — continuing."

# 2. Check Configuration & Determine Mode
OS="$(uname -s)"
# Detech AppData path (Matching StorageUtils logic)
CONFIG_DIR=""
if [ "$OS" = "Darwin" ]; then
    CONFIG_DIR="$HOME/Library/Application Support/wsbg-terminal"
else
    # Linux
    if [ -n "$XDG_DATA_HOME" ]; then
        CONFIG_DIR="$XDG_DATA_HOME/wsbg-terminal"
    else
        CONFIG_DIR="$HOME/.local/share/wsbg-terminal"
    fi
fi
CONFIG_FILE="$CONFIG_DIR/config.toml"

POWER_MODE=false

if [ -f "$CONFIG_FILE" ]; then
    echo "[*] Configuration found at: $CONFIG_FILE"
    if grep -q "power-mode\s*=\s*true" "$CONFIG_FILE"; then
        POWER_MODE=true
    fi
else
     echo "[*] No existing configuration found. Using defaults (Power Mode: OFF)."
fi

# 3. Select Models based on Mode
# Constant models
VISION_MODEL="glm-ocr:latest"
EMBED_MODEL="nomic-embed-text-v2-moe:latest"

# Variable models
REASONING_MODEL="qwen3.5:4b"
TRANSLATOR_MODEL="translategemma:4b"

if [ "$POWER_MODE" = true ]; then
    echo "[*] Power Mode: ON"
    REASONING_MODEL="qwen3.5:9b"
else
    echo "[*] Power Mode: OFF"
fi

echo "[*] Configuration Roadmap:"
echo "    - Reasoning Agent: $REASONING_MODEL"
echo "    - Translator:      $TRANSLATOR_MODEL"
echo "    - Vision/OCR:      $VISION_MODEL"
echo "    - Embeddings:      $EMBED_MODEL"


# 4. Pull Models (only if not already present)
INSTALLED_MODELS=$(ollama list 2>/dev/null | tail -n +2 | awk '{print $1}')

pull_if_missing() {
    # Case-insensitive match — ollama list may return names in different casing
    # than what we request (e.g. "GLM-OCR:latest" vs "glm-ocr:latest").
    if echo "$INSTALLED_MODELS" | grep -qi "^$1$"; then
        echo "    [OK] $1 already available"
    else
        echo "    > Pulling $1..."
        if ! ollama pull "$1"; then
            echo "    [WARN] Failed to pull $1 — continuing anyway"
        fi
    fi
}

pull_if_missing "$REASONING_MODEL"
pull_if_missing "$TRANSLATOR_MODEL"
pull_if_missing "$VISION_MODEL"
pull_if_missing "$EMBED_MODEL"

# 5. Generate Configuration File (if strictly new)
if [ ! -f "$CONFIG_FILE" ]; then
    echo "[*] Generating Application Configuration..."
    
    mkdir -p "$CONFIG_DIR"

    # Write TOML
    cat > "$CONFIG_FILE" <<EOL
# WSBG Terminal Configuration
# Auto-generated by setup.sh

debug-mode = false
ui-reddit-visible = true

[agent]
power-mode = false
ollama.vision-model = "${VISION_MODEL}"
ollama.embedding-model = "${EMBED_MODEL}"

[reddit]
# Add reddit settings here if needed
EOL

    echo "[*] Configuration written to: $CONFIG_FILE"
else
    echo "[*] Configuration already exists. Skipping generation."
fi

echo ""
echo "=========================================="
echo "   Setup Complete! Ready to Run.          "
echo "=========================================="
echo "Run using: .script/run.sh"
