
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "   WSBG Terminal - Setup & Installation   " -ForegroundColor Cyan
Write-Host "=========================================="
Write-Host ""

# 1. Check/Install Ollama
Write-Host "[*] Checking for Ollama..."
if (Get-Command "ollama" -ErrorAction SilentlyContinue) {
    Write-Host "    Ollama is already installed." -ForegroundColor Green
} else {
    Write-Host "    Ollama not found. Attempting to install via Winget..." -ForegroundColor Yellow
    try {
        winget install -e --id Ollama.Ollama --accept-source-agreements --accept-package-agreements
        if ($LASTEXITCODE -ne 0) {
            throw "Winget installation failed."
        }
        # Refresh env vars might be needed, but usually requires shell restart.
        Write-Host "    Ollama installed. You may need to restart the script/terminal for it to be recognized." -ForegroundColor Yellow
        Write-Host "    Attempting to continue..."
    } catch {
        Write-Host "    Failed to install Ollama automatically." -ForegroundColor Red
        Write-Host "    Please install it manually from https://ollama.com/download/windows"
        exit 1
    }
}

# Ensure Ollama is serving
if (!(Get-Process "ollama app" -ErrorAction SilentlyContinue)) {
    Write-Host "[*] Starting Ollama..."
    Start-Process "ollama" "serve" -WindowStyle Hidden
    Start-Sleep -Seconds 5
}

# 2. Detect RAM
$memObj = Get-CimInstance Win32_ComputerSystem
$ramGB = [math]::Round($memObj.TotalPhysicalMemory / 1GB)
Write-Host "[*] Detected System Memory: $ramGB GB" -ForegroundColor White

# 3. Determine Mode
$mode = "MED"
if ($ramGB -lt 8) {
    $mode = "LOW"
} elseif ($ramGB -ge 32) {
    $mode = "SUPER"
}

Write-Host "[*] Selected Optimization Mode: $mode" -ForegroundColor Cyan

# 4. Select Models
$visionModel = "glm-ocr:latest"
$embedModel = "nomic-embed-text-v2-moe:latest"
$functionModel = "functiongemma:latest"

$reasoningModel = "gemma3:12b"
$translatorModel = "translategemma:12b"

if ($mode -eq "LOW") {
    $reasoningModel = "gemma3:4b"
    $translatorModel = "translategemma:4b"
} elseif ($mode -eq "SUPER") {
    $reasoningModel = "gemma3:27b"
    $translatorModel = "translategemma:12b"
}

Write-Host "[*] Configuration Roadmap:" -ForegroundColor Gray
Write-Host "    - Reasoning Agent: $reasoningModel" -ForegroundColor Gray
Write-Host "    - Translator:      $translatorModel" -ForegroundColor Gray
Write-Host "    - Vision/OCR:      $visionModel" -ForegroundColor Gray
Write-Host "    - Embeddings:      $embedModel" -ForegroundColor Gray
Write-Host "    - Functions:       $functionModel" -ForegroundColor Gray

# 5. Pull Models
Write-Host "[*] Pulling models via Ollama (this may take a while)..." -ForegroundColor Yellow

function Pull-Model($modelName) {
    Write-Host "    > Pulling $modelName..."
    ollama pull $modelName
}

Pull-Model $reasoningModel
Pull-Model $translatorModel
Pull-Model $visionModel
Pull-Model $embedModel
Pull-Model $functionModel

# 6. Generate Config
Write-Host "[*] Generating Application Configuration..."

$appDataPath = $env:APPDATA
if ([string]::IsNullOrEmpty($appDataPath)) {
    $appDataPath = [System.IO.Path]::Combine($env:USERPROFILE, "AppData", "Roaming")
}

$configDir = [System.IO.Path]::Combine($appDataPath, "wsbg-terminal")
if (!(Test-Path $configDir)) {
    New-Item -ItemType Directory -Force -Path $configDir | Out-Null
}

$configFile = [System.IO.Path]::Combine($configDir, "config.toml")

$configContent = @"
# WSBG Terminal Configuration
# Auto-generated by setup.bat based on detected hardware ($ramGB GB RAM)
# Mode: $mode

debug-mode = false
ui-reddit-visible = true

[agent]
ollama.model = "$reasoningModel"
ollama.translator-model = "$translatorModel"
ollama.vision-model = "$visionModel"
ollama.embedding-model = "$embedModel"

[reddit]
# Add reddit settings here if needed
"@

Set-Content -Path $configFile -Value $configContent -Encoding utf8

Write-Host "[*] Configuration written to: $configFile" -ForegroundColor Green
Write-Host ""
Write-Host "Setup Complete! Ready to Run." -ForegroundColor Green
Exit 0
