name: 'TinyUpdate Package'
description: 'Packages application artifacts with SHA-256 manifest for OTA distribution'

inputs:
  artifact-dirs:
    description: 'Comma-separated list of directories containing JARs to package (e.g. "ui/target,core/target")'
    required: true
  script-dir:
    description: 'Directory containing setup scripts to bundle'
    required: false
    default: '.script'
  output-dir:
    description: 'Output directory for files.zip and update.json'
    required: false
    default: 'updater-dist'

outputs:
  manifest-path:
    description: 'Path to the generated update.json'
    value: ${{ steps.package.outputs.manifest-path }}
  zip-path:
    description: 'Path to the generated files.zip'
    value: ${{ steps.package.outputs.zip-path }}

runs:
  using: 'composite'
  steps:
    - name: Package for TinyUpdate
      id: package
      shell: bash
      run: |
        set -euo pipefail

        OUTPUT_DIR="${{ inputs.output-dir }}"
        STAGING_DIR="$OUTPUT_DIR/staging"
        ARTIFACT_DIRS="${{ inputs.artifact-dirs }}"
        SCRIPT_DIR="${{ inputs.script-dir }}"
        TAG_NAME="${GITHUB_REF_NAME:-unknown}"

        mkdir -p "$STAGING_DIR/lib"
        mkdir -p "$STAGING_DIR/bin"

        echo "=== TinyUpdate Packager ==="
        echo "Tag: $TAG_NAME"
        echo "Artifact dirs: $ARTIFACT_DIRS"

        # --- 1. Collect JARs ---
        declare -A JAR_MAP  # basename -> full path (latest version wins for dedup)

        IFS=',' read -ra DIRS <<< "$ARTIFACT_DIRS"
        for dir in "${DIRS[@]}"; do
          dir=$(echo "$dir" | xargs)  # trim whitespace
          if [ ! -d "$dir" ]; then
            echo "Warning: directory $dir not found, skipping"
            continue
          fi

          for jar in "$dir"/*.jar; do
            [ -f "$jar" ] || continue

            basename=$(basename "$jar")

            # Skip sources/javadoc JARs
            if [[ "$basename" == *-sources.jar ]] || [[ "$basename" == *-javadoc.jar ]]; then
              continue
            fi

            # Dedup by full filename — only identical JARs from different dirs collapse.
            # Previous regex stripped classifiers, incorrectly merging e.g.
            # javafx-web-25-ea+1-mac-aarch64.jar with javafx-web-25-ea+1.jar.
            if [ -n "${JAR_MAP[$basename]+x}" ]; then
              existing="${JAR_MAP[$basename]}"
              echo "  Dedup: replacing $(basename "$existing") with $basename"
            fi
            JAR_MAP["$basename"]="$jar"
          done
        done

        echo "Collected ${#JAR_MAP[@]} unique JARs"

        for jar_path in "${JAR_MAP[@]}"; do
          cp "$jar_path" "$STAGING_DIR/lib/"
        done

        # --- 2. Collect Scripts ---
        if [ -d "$SCRIPT_DIR" ]; then
          for script in "$SCRIPT_DIR"/setup.*; do
            [ -f "$script" ] || continue
            cp "$script" "$STAGING_DIR/bin/"
            echo "Bundled script: $(basename "$script")"
          done
        fi

        # --- 3. Generate Manifest ---
        echo "Generating update.json..."

        MANIFEST="$OUTPUT_DIR/update.json"
        echo '{' > "$MANIFEST"
        echo "  \"version\": \"$TAG_NAME\"," >> "$MANIFEST"
        echo '  "files": [' >> "$MANIFEST"

        FIRST=true
        find "$STAGING_DIR" -type f | sort | while read -r file; do
          rel_path="${file#$STAGING_DIR/}"
          sha256=$(shasum -a 256 "$file" | cut -d' ' -f1)
          size=$(stat -f%z "$file" 2>/dev/null || stat --printf="%s" "$file" 2>/dev/null)

          if [ "$FIRST" = true ]; then
            FIRST=false
          else
            echo ',' >> "$MANIFEST"
          fi

          printf '    { "path": "%s", "sha256": "%s", "size": %s }' "$rel_path" "$sha256" "$size" >> "$MANIFEST"
        done

        echo '' >> "$MANIFEST"
        echo '  ]' >> "$MANIFEST"
        echo '}' >> "$MANIFEST"

        echo "Manifest generated with $(grep -c '"path"' "$MANIFEST") entries"

        # --- 4. Create Zip ---
        echo "Creating files.zip..."
        cd "$STAGING_DIR"
        zip -r "../files.zip" . -x '.*'
        cd -

        echo "=== Packaging Complete ==="
        echo "manifest-path=$OUTPUT_DIR/update.json" >> "$GITHUB_OUTPUT"
        echo "zip-path=$OUTPUT_DIR/files.zip" >> "$GITHUB_OUTPUT"
