package de.bsommerfeld.signals.processor;

import java.util.Collection;
import java.util.stream.Collectors;

/**
 * Writes {@code Signals}, the class a register imports {@code signal} from: one
 * overload per view, each taking that view's {@code Ref}. The overloads differ
 * in their parameter type, so {@code signal(DashboardView::new)} selects exactly
 * one of them, and its stubs are all the IDE offers after the dot.
 */
final class EntrySource {

    static final String SIMPLE_NAME = "Signals";

    private final String packageName;
    private final Collection<String> generatedClasses;

    /** @param generatedClasses the qualified names of the {@code ViewSignals} classes */
    EntrySource(String packageName, Collection<String> generatedClasses) {
        this.packageName = packageName;
        this.generatedClasses = generatedClasses;
    }

    String qualifiedName() {
        return packageName.isEmpty() ? SIMPLE_NAME : packageName + "." + SIMPLE_NAME;
    }

    String render() {
        String packageLine = packageName.isEmpty() ? "" : "package " + packageName + ";\n";
        return """
                // Generated by the signals processor. Do not edit.
                %s
                /** The signals of every view in this module: {@code signal(View::new)} lists that view's. */
                public final class %s {

                    private %s() {
                    }
                %s}
                """.formatted(packageLine, SIMPLE_NAME, SIMPLE_NAME, generatedClasses.stream()
                .sorted()
                .map(EntrySource::overload)
                .collect(Collectors.joining()));
    }

    private static String overload(String generatedClass) {
        return """

                    public static %s signal(%s.%s view) {
                        return new %s();
                    }
                """.formatted(generatedClass, generatedClass, SignalOwner.REFERENCE_NAME, generatedClass);
    }
}
