package de.bsommerfeld.signals.processor;

import de.bsommerfeld.signals.Signal;
import de.bsommerfeld.signals.SignalEmitter;
import de.bsommerfeld.signals.SignalStub;
import de.bsommerfeld.signals.SignalType;

import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.ArrayType;
import javax.lang.model.type.PrimitiveType;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Types;
import java.util.List;
import java.util.function.BiConsumer;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Writes {@code ViewSignals} for one {@link SignalOwner}: a stub per signal,
 * the {@code Ref} that {@code View::new} converts to, and the nested subclass
 * {@code Emitter} that repeats every inheritable constructor - annotations
 * included, so an injector builds it like the view - and overrides every
 * signal method to report the call once the method has run.
 */
final class SignalsSource {

    private static final String SINK_FIELD = "signalSink";
    private static final String SEND_METHOD = "sendSignal";

    /* The runtime types the generated code refers to, fully qualified. */
    private static final String SIGNAL_STUB = SignalStub.class.getName();
    private static final String SIGNAL_TYPE = SignalType.class.getName();
    private static final String SIGNAL_EMITTER = SignalEmitter.class.getName();
    private static final String SINK = BiConsumer.class.getName() + "<" + SIGNAL_STUB + "<?, ?>, java.lang.Object>";

    private final SignalOwner owner;
    private final Types types;
    private final String ownerName;

    SignalsSource(SignalOwner owner, Types types) {
        this.owner = owner;
        this.types = types;
        this.ownerName = owner.type().getQualifiedName().toString();
    }

    String render() {
        return header()
                + "public final class %s {\n".formatted(owner.generatedSimpleName())
                + joined(owner.signals(), this::stubConstant)
                + reference()
                + constructor()
                + joined(owner.signals(), this::stubAccessor)
                + emitter()
                + "}\n";
    }

    private String header() {
        String packageLine = owner.packageName().isEmpty() ? "" : "package " + owner.packageName() + ";\n";
        return """
                // Generated by the signals processor from %s. Do not edit.
                %s
                /** The signals {@link %s} declares, as stubs to wire in a register. */
                """.formatted(ownerName, packageLine, ownerName);
    }

    private String stubConstant(ExecutableElement signal) {
        return """

                    private static final %s<%s, %s> %s =
                            new %s<>(%s.class, "%s", %s.%s);
                """.formatted(SIGNAL_STUB, ownerName, payloadType(signal), SignalOwner.constantName(signal),
                SIGNAL_STUB, ownerName, signal.getSimpleName(), SIGNAL_TYPE, signalType(signal));
    }

    private String reference() {
        ExecutableElement constructor = owner.publicConstructor().orElseThrow();
        return """

                    /** What {@code %s::new} converts to in {@code Signals.signal(...)}; never called. */
                    @java.lang.FunctionalInterface
                    public interface %s {
                        %s create(%s)%s;
                    }
                """.formatted(owner.type().getSimpleName(), SignalOwner.REFERENCE_NAME, ownerName,
                parameters(constructor), throwsClause(constructor));
    }

    private String constructor() {
        return """

                    /** For the generated {@code Signals}. */
                    public %s() {
                    }
                """.formatted(owner.generatedSimpleName());
    }

    private String stubAccessor(ExecutableElement signal) {
        return """

                    /** {@link %s#%s} */
                    public %s<%s, %s> %s() {
                        return %s;
                    }
                """.formatted(ownerName, signal.getSimpleName(), SIGNAL_STUB, ownerName, payloadType(signal),
                signal.getSimpleName(), SignalOwner.constantName(signal));
    }

    private String emitter() {
        return """

                    static final class %s extends %s implements %s {

                        private %s %s;
                """.formatted(SignalOwner.EMITTER_NAME, ownerName, SIGNAL_EMITTER, SINK, SINK_FIELD)
                + joined(owner.inheritableConstructors(), this::emitterConstructor)
                + """

                        @Override
                        public void connectSignals(%s sink) {
                            if (%s != null) {
                                throw new IllegalStateException("this %s is connected already");
                            }
                            %s = java.util.Objects.requireNonNull(sink, "sink");
                        }
                """.formatted(SINK, SINK_FIELD, owner.type().getSimpleName(), SINK_FIELD)
                + joined(owner.signals(), this::signalOverride)
                + """

                        private void %s(%s<?, ?> signal, java.lang.Object payload) {
                            if (%s == null) {
                                throw new IllegalStateException(signal + " was sent before the view was registered"
                                        + " - signals cannot be sent from a constructor");
                            }
                            %s.accept(signal, payload);
                        }
                    }
                """.formatted(SEND_METHOD, SIGNAL_STUB, SINK_FIELD, SINK_FIELD);
    }

    private String emitterConstructor(ExecutableElement constructor) {
        return """

                        %s%s%s(%s)%s {
                            super(%s);
                        }
                """.formatted(annotations(constructor.getAnnotationMirrors(), "\n        "),
                visibility(constructor), SignalOwner.EMITTER_NAME,
                parameters(constructor), throwsClause(constructor), arguments(constructor));
    }

    private String signalOverride(ExecutableElement signal) {
        String payload = signal.getParameters().isEmpty() ? "null" : arguments(signal);
        return """

                        @Override
                        %svoid %s(%s)%s {
                            super.%s(%s);
                            %s(%s, %s);
                        }
                """.formatted(visibility(signal), signal.getSimpleName(), parameters(signal),
                throwsClause(signal), signal.getSimpleName(), arguments(signal),
                SEND_METHOD, SignalOwner.constantName(signal), payload);
    }

    /** The stub's payload type: the parameter type, boxed, or {@code Void}. */
    private String payloadType(ExecutableElement signal) {
        if (signal.getParameters().isEmpty()) {
            return "java.lang.Void";
        }
        TypeMirror type = signal.getParameters().getFirst().asType();
        return type.getKind().isPrimitive()
                ? types.boxedClass((PrimitiveType) type).getQualifiedName().toString()
                : type.toString();
    }

    /** The {@code SignalType} constant named in {@code @Signal(...)}, the annotation's default if none is. */
    private static String signalType(ExecutableElement signal) {
        return signal.getAnnotationMirrors().stream()
                .filter(mirror -> mirror.getAnnotationType().toString().equals(
                        Signal.class.getCanonicalName()))
                .flatMap(mirror -> mirror.getElementValues().values().stream())
                .map(AnnotationValue::getValue)
                .map(Object::toString)
                .findFirst()
                .orElse(SignalType.CHANGE_VIEW.name());
    }

    private String parameters(ExecutableElement method) {
        List<? extends VariableElement> parameters = method.getParameters();
        return parameters.stream()
                .map(parameter -> annotations(parameter.getAnnotationMirrors(), " ")
                        + parameterType(method, parameter) + " " + parameter.getSimpleName())
                .collect(Collectors.joining(", "));
    }

    private static String parameterType(ExecutableElement method, VariableElement parameter) {
        boolean varargs = method.isVarArgs() && parameter == method.getParameters().getLast();
        return varargs ? ((ArrayType) parameter.asType()).getComponentType() + "..." : parameter.asType().toString();
    }

    private static String arguments(ExecutableElement method) {
        return method.getParameters().stream()
                .map(parameter -> parameter.getSimpleName().toString())
                .collect(Collectors.joining(", "));
    }

    private static String throwsClause(ExecutableElement method) {
        return method.getThrownTypes().isEmpty() ? "" : " throws " + method.getThrownTypes().stream()
                .map(TypeMirror::toString)
                .collect(Collectors.joining(", "));
    }

    private static String visibility(ExecutableElement element) {
        return Stream.of(Modifier.PUBLIC, Modifier.PROTECTED)
                .filter(element.getModifiers()::contains)
                .map(modifier -> modifier + " ")
                .findFirst()
                .orElse("");
    }

    private static String annotations(List<? extends AnnotationMirror> annotations, String separator) {
        return annotations.stream()
                .map(annotation -> annotation + separator)
                .collect(Collectors.joining());
    }

    private static <T> String joined(List<T> items, Function<T, String> render) {
        return items.stream().map(render).collect(Collectors.joining());
    }
}
