package de.bsommerfeld.signals.processor;

import de.bsommerfeld.signals.SignalConnection;
import de.bsommerfeld.signals.SignalEmitter;
import de.bsommerfeld.signals.SignalKey;
import de.bsommerfeld.signals.Signaling;

import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.ArrayType;
import javax.lang.model.type.PrimitiveType;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Types;
import java.util.List;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Writes {@code OwnerSignals} for one {@link SignalOwner}: a key constant and a
 * static accessor per signal, and the nested subclass {@code Emitting} that
 * repeats every inheritable constructor - annotations included, so an injector
 * builds it like the owner - and overrides every signal method to report the
 * call once the method has run.
 */
final class SignalsSource {

    private static final String CONNECTION_FIELD = "signalConnection";

    /* The runtime types the generated code refers to, fully qualified. */
    private static final String SIGNAL_KEY = SignalKey.class.getName();
    private static final String SIGNALING = Signaling.class.getName();
    private static final String SIGNAL_EMITTER = SignalEmitter.class.getName();
    private static final String SIGNAL_CONNECTION = SignalConnection.class.getName();

    private final SignalOwner owner;
    private final Types types;
    private final String ownerName;

    SignalsSource(SignalOwner owner, Types types) {
        this.owner = owner;
        this.types = types;
        this.ownerName = owner.type().getQualifiedName().toString();
    }

    String render() {
        return header()
                + "%sfinal class %s {\n".formatted(owner.isPublic() ? "public " : "", owner.generatedSimpleName())
                + joined(owner.signals(), this::keyConstant)
                + noInstances()
                + joined(owner.signals(), this::keyAccessor)
                + implementation()
                + "}\n";
    }

    private String header() {
        String packageLine = owner.packageName().isEmpty() ? "" : "package " + owner.packageName() + ";\n";
        return """
                // Generated by the signals processor from %s. Do not edit.
                %s
                /** The signals {@link %s} declares, to bind in a scope. */
                """.formatted(ownerName, packageLine, ownerName);
    }

    private String noInstances() {
        return """

                    private %s() {
                    }
                """.formatted(owner.generatedSimpleName());
    }

    private String implementation() {
        return """

                    static final class %s extends %s implements %s {

                        private final %s %s = new %s(%s.class);
                """.formatted(SignalOwner.IMPLEMENTATION_NAME, ownerName, SIGNALING,
                SIGNAL_CONNECTION, CONNECTION_FIELD, SIGNAL_CONNECTION, ownerName)
                + joined(owner.inheritableConstructors(), this::constructor)
                + """

                        @Override
                        public void connectSignals(%s emitter) {
                            %s.connect(emitter);
                        }
                """.formatted(SIGNAL_EMITTER, CONNECTION_FIELD)
                + joined(owner.signals(), this::signalOverride)
                + "    }\n";
    }

    private String keyConstant(ExecutableElement signal) {
        return """

                    private static final %s<%s> %s = %s.of(%s.class, "%s");
                """.formatted(SIGNAL_KEY, payloadType(signal), SignalOwner.constantName(signal),
                SIGNAL_KEY, ownerName, signal.getSimpleName());
    }

    private String keyAccessor(ExecutableElement signal) {
        return """

                    /** Sent when {@link %s#%s} has run. */
                    public static %s<%s> %s() {
                        return %s;
                    }
                """.formatted(ownerName, signal.getSimpleName(), SIGNAL_KEY, payloadType(signal),
                signal.getSimpleName(), SignalOwner.constantName(signal));
    }

    private String constructor(ExecutableElement constructor) {
        return """

                        %s%s%s(%s)%s {
                            super(%s);
                        }
                """.formatted(annotations(constructor.getAnnotationMirrors(), "\n        "),
                visibility(constructor), SignalOwner.IMPLEMENTATION_NAME,
                parameters(constructor), throwsClause(constructor), arguments(constructor));
    }

    private String signalOverride(ExecutableElement signal) {
        String payload = signal.getParameters().isEmpty() ? "null" : arguments(signal);
        return """

                        @Override
                        %svoid %s(%s)%s {
                            super.%s(%s);
                            %s.emit(%s, %s);
                        }
                """.formatted(visibility(signal), signal.getSimpleName(), parameters(signal),
                throwsClause(signal), signal.getSimpleName(), arguments(signal),
                CONNECTION_FIELD, SignalOwner.constantName(signal), payload);
    }

    /** The key's type argument: the parameter type, boxed, or {@code Void}. */
    private String payloadType(ExecutableElement signal) {
        if (signal.getParameters().isEmpty()) {
            return "java.lang.Void";
        }
        TypeMirror type = signal.getParameters().getFirst().asType();
        return type.getKind().isPrimitive()
                ? types.boxedClass((PrimitiveType) type).getQualifiedName().toString()
                : type.toString();
    }

    private String parameters(ExecutableElement method) {
        List<? extends VariableElement> parameters = method.getParameters();
        return parameters.stream()
                .map(parameter -> annotations(parameter.getAnnotationMirrors(), " ")
                        + parameterType(method, parameter) + " " + parameter.getSimpleName())
                .collect(Collectors.joining(", "));
    }

    private static String parameterType(ExecutableElement method, VariableElement parameter) {
        boolean varargs = method.isVarArgs() && parameter == method.getParameters().getLast();
        return varargs ? ((ArrayType) parameter.asType()).getComponentType() + "..." : parameter.asType().toString();
    }

    private static String arguments(ExecutableElement method) {
        return method.getParameters().stream()
                .map(parameter -> parameter.getSimpleName().toString())
                .collect(Collectors.joining(", "));
    }

    private static String throwsClause(ExecutableElement method) {
        return method.getThrownTypes().isEmpty() ? "" : " throws " + method.getThrownTypes().stream()
                .map(TypeMirror::toString)
                .collect(Collectors.joining(", "));
    }

    private static String visibility(ExecutableElement element) {
        return Stream.of(Modifier.PUBLIC, Modifier.PROTECTED)
                .filter(element.getModifiers()::contains)
                .map(modifier -> modifier + " ")
                .findFirst()
                .orElse("");
    }

    private static String annotations(List<? extends AnnotationMirror> annotations, String separator) {
        return annotations.stream()
                .map(annotation -> annotation + separator)
                .collect(Collectors.joining());
    }

    private static <T> String joined(List<T> items, Function<T, String> render) {
        return items.stream().map(render).collect(Collectors.joining());
    }
}
